### ISSUE TITLE
using bind mount for aktin.properties (suggestion)

### ISSUE THREAD

**Issue by MaikLoewe** [aktin/docker-aktin-dwh#10]
Hello everyone,

currently, the configuration file is written to a docker volume and must be edited via sudo or root in the directory ‘/var/lib/docker/volumes’.

I would like to suggest using this as a so-called ‘bind mount’ from the directory of the docker compose configuration.
https://docs.docker.com/engine/storage/bind-mounts/

In conjunction with the suggestion to use individual directories for the respective docker-compose.yml, it could look like this:

```  
wildfly:
    image: ghcr.io/aktin/notaufnahme-dwh-wildfly:1.6rc1-2-docker2
    hostname: wildfly
    restart: unless-stopped
    environment:
      DB_HOST: database
      DB_PORT: 5432
    volumes:
#      - aktin_config:/etc/aktin
      - ./aktin.properties:/opt/wildfly/standalone/configuration/aktin.properties
      - aktin_data:/var/lib/aktin
```

In conjunction with the directory structure mentioned in Issue #7, it could work like this:

```  
-> /opt/docker-deploy/
    -> /aktin-dwh1
        - docker-compose.yml
        - aktin.properties
```

Best regards
