### ISSUE TITLE
how to configure http and https proxy setting for docker services httpd and wildfly (question)

### ISSUE THREAD

**Issue by MaikLoewe** [aktin/docker-aktin-dwh#16]
Hello everyone,

according to the network (https://aktin.org/software/1.5.1/server/network.html) instructions, the components must be able to communicate with the Internet in order for the AKTIN DWH to operate.

In a native installation under Ubuntu 22.04, it is possible to write the proxy in `/etc/environments` and for Wildfly, `/opt/wildfly/bin/standalone.conf` must be extended with "JAVA_OPTS".

This is also possible in Docker, but it is cumbersome and not a good idea. However, there is still the option of defining JAVA_OPTS via the environment variables of the respective service.

If I follow the example of other Java applications, I can use the following option:

```
    environment:
      DB_HOST: database
      DB_PORT: 5432
      JAVA_OPTS: -Dhttp.proxyHost=our-proxy.that-domain.org -Dhttp.proxyPort=80 -Dhttps.proxyHost=our-proxy.that-domain.org -Dhttps.proxyPort=80 -Dhttp.nonProxyHosts="localhost|10.*|172.*"
```

I now set this in our environment, but can you tell me how I can check the connection?

Best regards
