### ISSUE TITLE
Brauchen wir wirklich den httpd Container in der docker-compose.yml? (question)

### ISSUE THREAD

**Issue by MaikLoewe** [aktin/docker-aktin-dwh#17]
Hello everyone,
I was working on the health_check #9 issue with the WildFly container and wondered whether it would be possible to deliver the web application directly from this container.

Since we deliver the containers via Traefik in our setup and use so-called labels for this purpose, I attached the label from the httpd container to the Wildfly and lo and behold, the application also runs directly via Wildfly behind a reverse proxy.

```
    depends_on:
      database:
        condition: service_healthy
# deactivated because not support at the moment, fix in progress 
#    healthcheck:
#      test: [ "CMD", "curl", "-s", "-o", "/dev/null", "-w", "%{http_code}", "http://localhost:8080/aktin/admin/rest/info/version", "|", "grep", "200" ]
#      interval: 30s
#      timeout: 10s
#      retries: 10
#      start_period: 120s
    networks:
      - backend
      - frontend

    labels:
      - traefik.enable=True
      - traefik.http.routers.aktin-dwh.rule=Host(`aktin-zna.test.med.tu-dresden.de`)
      - traefik.http.routers.aktin-dwh.tls.certresolver=our-fancy-resolver
      - traefik.http.routers.aktin-dwh.service=aktin-dwh
      - traefik.http.routers.aktin-dwh.entrypoints=https
      - traefik.http.services.aktin-dwh.loadbalancer.server.port=9090
```
I can access the admin test page and the i2b2 webclient.
So my question is, does the httpd have any additional tasks beyond those of Wildfly, or can we do without the container?

Best regards
