### ISSUE TITLE
Refactor and cleanup `compose.yml`

### ISSUE THREAD

**Issue by akomii** [aktin/docker-aktin-dwh#25]
Make small improvements to `compose.yml` to increase flexibility and maintainability:

- [ ] ~Move image name into a variable~
- [x] Move container version int a variable
- [x] Move all configurable values into .env
- [ ] ~Configure httpd to use two networks (one internal, one external)~

```
networks:
    frontend:
        name: xxx
        external: true
    backend:
        name: yyy
```

- [x] Check if `hostname` is necessary or the service name is used as a default
- [x] Check if `driver: local`  is necessary or used as Dockers default 
- [x] Check if `driver: bridge` is necessary or used as Dockers default
